### PR TITLE
bug/4: Made class list generation more stable

### LINKED ISSUE #4: Class list generation is unstable
Due to concurrency and external resources the test can load different classes in different builds.
That makes the class list verifier unstable.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #4

### CODE REVIEW

File: verifier/src/main/java/com/exasol/classlistextractor/verifier/ClassListExtractor.java [hunk 1]
```diff
@@ -58,9 +58,41 @@ public ClassListExtractor(final Bucket bucket, final LocalServiceExposer service
      */
     public List<String> capture(final CallbackWithQueryToScript runnable) {
         assertGetJvmOptionsWasCalled();
+        final List<Set<String>> classLists = new ArrayList<>();
+        for (int run = 0; run < 5; run++) {
+            classLists.add(recordClassLoading(runnable));
+        }
+        // By building the intersection of multiple runs we make the result more stable since flanky classes are removed
```
Comment (kaklakariada) [inline verifier/src/main/java/com/exasol/classlistextractor/verifier/ClassListExtractor.java]:
```suggestion
        // By building the intersection of multiple runs we make the result more stable since flaky classes are removed.
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — APPROVED** [review]
